@startuml bakery

hide empty members

class INGREDIENT {
    -name : String
}

class INGREDIENT_COST {
    -start_date : Date
    -end_date : Date
    -cost_per_gram : double
}

INGREDIENT "1" - "0..*" INGREDIENT_COST : has >

class DISH {
    -name : String
    -price : double
    -weight_in_grams : double
}

class USAGE {
    -weight_in_grams : double
}

USAGE "0..*" - "1" INGREDIENT : contains >
DISH "1" - "0..*" USAGE : uses >

@enduml
