@startuml bakery

hide empty members

class Ingredient {
    -name : String
}

class IngredientCost {
    -start_date : Date
    -end_date : Date
    -cost_per_gram : double
}

Ingredient "1" -- "0..*" IngredientCost : has >

class Dish {
    -name : String
    -price : double
    -weight_in_grams : double
}

class Usage {
    -weight_in_grams : double
}

Usage "0..*" - "1" Ingredient : contains >
Dish "1" - "0..*" Usage : uses >

@enduml
